### ISSUE TITLE
Collect Dataset

### ISSUE THREAD

**Issue by AshiishKarhade** [AshiishKarhade/COVID-19-Prediction-using-Chest-X-Ray-Images#1]
We have to collect dataset from different resources. The more data we have, the more accurate our model will be

**Comment by CadmusFlux** [comment]
Hey Ashish , I would be happy to assist in helping to collect dataset .

**Comment by AshiishKarhade** [comment]
@CadmusFlux 
The project has been completed from our end. 
If you want to help to improve the overall accuracy, we would love to see your version of the current project. 
You can fork the project and show your version of project
